[workspace]
resolver = "2"

members = [
    "metatensor-core",
    "metatensor-torch",
    "rust/metatensor",
    "rust/metatensor-sys",
    "python",
]


[patch.crates-io]
dlpk = { git = "https://github.com/HaoZeke/dlpack-fork", branch="upd_1.2" }
